/*
 * POST /api/practise/generate
 *
 * Builds a "Practise" - the middle rung between Quiz me and Test me.
 *
 * Stage one is always written from the student's own notes and works on any
 * page in any subject, but it comes in two shapes. Where real exam questions
 * follow, it is rapid recall: short, hard, one-sentence answers, the quiz typed
 * rather than clicked. Where they do not, it is the longer explain-and-develop
 * stage, because then it is the whole test.
 *
 * Stage two is real exam questions, and is only ever built where the actual
 * structure of the exam is known - which today means AQA GCSE History. It is
 * generated by the same prompt and the same registry the mock papers use, so
 * the questions are the questions Test me would set, with the real marks, the
 * real SPaG marks and the real mark scheme. Everywhere else there is no stage
 * two at all: stage one is simply longer.
 */
import { callGemini, lastModelUsed } from "../test/generate.js";
import { COMPONENTS, optionById, buildGenerationPrompt } from "../../src/exam/aqaHistory.js";
import {
  MIN_PRACTISE_WORDS,
  MAX_NOTE_CHARS,
  clampTarget,
  planKnowledge,
  examBudgetMinutes,
  selectExamQuestions,
  allowedMinutes,
  buildKnowledgePrompt,
  buildRecallPrompt
} from "../../src/practise/prompt.js";
import { requireUser } from "../_lib/auth.js";

const KNOWLEDGE_SCHEMA = {
  type: "OBJECT",
  properties: {
    title: { type: "STRING" },
    questions: {
      type: "ARRAY",
      items: {
        type: "OBJECT",
        properties: {
          number: { type: "INTEGER" },
          prompt: { type: "STRING" },
          marks: { type: "INTEGER" },
          rubric: { type: "ARRAY", items: { type: "STRING" } },
          modelAnswer: { type: "STRING" },
          topic: { type: "STRING" }
        },
        required: ["number", "prompt", "marks", "rubric", "modelAnswer", "topic"]
      }
    }
  },
  required: ["questions"]
};

const PAPER_SCHEMA = {
  type: "OBJECT",
  properties: {
    focusSummary: { type: "STRING" },
    sources: {
      type: "ARRAY",
      items: {
        type: "OBJECT",
        properties: {
          label: { type: "STRING" },
          provenance: { type: "STRING" },
          body: { type: "STRING" }
        },
        required: ["label", "provenance", "body"]
      }
    },
    questions: {
      type: "ARRAY",
      items: {
        type: "OBJECT",
        properties: {
          number: { type: "INTEGER" },
          stem: { type: "STRING" },
          usesSources: { type: "ARRAY", items: { type: "STRING" } },
          markScheme: {
            type: "OBJECT",
            properties: {
              levels: {
                type: "ARRAY",
                items: {
                  type: "OBJECT",
                  properties: {
                    level: { type: "STRING" },
                    markRange: { type: "STRING" },
                    descriptor: { type: "STRING" }
                  },
                  required: ["level", "markRange", "descriptor"]
                }
              },
              indicativeContent: { type: "ARRAY", items: { type: "STRING" } }
            },
            required: ["levels", "indicativeContent"]
          }
        },
        required: ["number", "stem", "markScheme"]
      }
    }
  },
  required: ["sources", "questions"]
};

function send(res, status, payload) {
  res.setHeader("Content-Type", "application/json; charset=utf-8");
  res.setHeader("Cache-Control", "no-store");
  res.status(status).send(JSON.stringify(payload));
}

async function readBody(req) {
  if (req.body && typeof req.body === "object") return req.body;
  if (typeof req.body === "string") return JSON.parse(req.body);
  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  return JSON.parse(Buffer.concat(chunks).toString("utf8") || "{}");
}

function normaliseKnowledge(raw, number, style) {
  const recall = style === "recall";
  const prompt = String(raw.prompt || "").trim();
  if (!prompt) return null;
  let marks = Math.round(Number(raw.marks) || 0);
  if (recall) {
    // Recall questions are two marks each by definition, whatever the model says.
    if (!marks || marks < 1) marks = 2;
    if (marks > 3) marks = 2;
  } else {
    if (!marks || marks < 2) marks = 3;
    if (marks > 6) marks = 6;
  }
  const rubric = (Array.isArray(raw.rubric) ? raw.rubric : [])
    .map((r) => String(r || "").trim())
    .filter(Boolean)
    .slice(0, recall ? 3 : 8);
  if (rubric.length < (recall ? 1 : 2)) return null;
  // The marks a question is worth can never exceed the number of distinct
  // points the mark scheme actually lists.
  if (marks > rubric.length) marks = rubric.length;
  return {
    number,
    prompt,
    marks,
    rubric,
    modelAnswer: String(raw.modelAnswer || "").trim(),
    topic: String(raw.topic || "").trim().slice(0, 60)
  };
}

/* The exam stage: generate the real paper, then set only as much of it as fits
   the practise. Nothing about the questions is rescaled. */
async function buildExamStage(cfg, apiKey) {
  const component = COMPONENTS[cfg.componentId];
  const option = optionById(cfg.optionId);
  if (!component || !option || option.componentId !== component.id) return null;

  const budget = examBudgetMinutes(cfg.targetMinutes);
  const chosen = selectExamQuestions(component.questions, budget, cfg.capMinutes);
  if (!chosen.length) return null;

  const prompt = buildGenerationPrompt({
    componentId: component.id,
    optionId: option.id,
    site: cfg.site,
    pageTitle: cfg.pageTitle,
    includedPages: cfg.includedPages,
    notes: cfg.notes
  });

  const generated = await callGemini(prompt.system, prompt.user, PAPER_SCHEMA, apiKey);

  const byNumber = {};
  (generated.questions || []).forEach((q) => {
    byNumber[String(q.number)] = q;
  });

  // Marks, timings, SPaG and question order come from the specification, never
  // from the model, exactly as they do for a full mock paper.
  const questions = chosen.map((spec) => {
    const g = byNumber[String(spec.n)] || {};
    return {
      number: spec.n,
      stem: String(g.stem || "").trim() || "(This question failed to generate \u2014 skip it.)",
      marks: spec.marks,
      spagMarks: spec.spag,
      ao: spec.ao,
      guidanceMinutes: spec.minutes,
      usesSources: spec.uses,
      markScheme: g.markScheme || { levels: [], indicativeContent: [] }
    };
  });

  // Only the stimulus material the set questions actually use is included.
  const needed = {};
  questions.forEach((q) => (q.usesSources || []).forEach((label) => (needed[label] = true)));
  const sources = (generated.sources || [])
    .map((s) => ({
      label: String(s.label || "").trim(),
      provenance: String(s.provenance || "").trim(),
      body: String(s.body || "").trim(),
      synthetic: true
    }))
    .filter((s) => Object.keys(needed).some((label) => s.label && label.indexOf(s.label) > -1));

  const marks = questions.reduce((sum, q) => sum + q.marks + (q.spagMarks || 0), 0);
  const minutes = questions.reduce((sum, q) => sum + q.guidanceMinutes, 0);

  return {
    componentId: component.id,
    optionId: option.id,
    paperTitle: component.paper,
    sectionTitle: component.section,
    componentShort: component.short,
    optionLabel: option.label,
    site: cfg.site || "",
    focusSummary: String(generated.focusSummary || "").slice(0, 300),
    marks,
    minutes,
    sources,
    questions
  };
}

export default async function handler(req, res) {
  if (req.method === "OPTIONS") return send(res, 204, {});
  if (req.method !== "POST") return send(res, 405, { error: "Use POST." });

  const user = await requireUser(req, res, send);
  if (!user) return;

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return send(res, 500, {
      error: "No Gemini API key is configured. Add GEMINI_API_KEY in your Vercel project settings and redeploy."
    });
  }

  let body;
  try {
    body = await readBody(req);
  } catch (e) {
    return send(res, 400, { error: "Could not read the request." });
  }

  const notes = String(body.notes || "").slice(0, MAX_NOTE_CHARS);
  const words = notes.trim() ? notes.trim().split(/\s+/).length : 0;
  if (words < MIN_PRACTISE_WORDS) {
    return send(res, 400, { error: "There aren't enough notes here to build a practise from." });
  }

  const targetMinutes = clampTarget(body.targetMinutes);
  const pageTitle = String(body.pageTitle || "").slice(0, 200);
  const subjectTitle = String(body.subjectTitle || "").slice(0, 200);
  const includedPages = Array.isArray(body.includedPages) ? body.includedPages.slice(0, 40) : [];

  // An exam stage is only ever attempted when the caller names a component and
  // option that exist in the registry. No registry, no exam questions.
  const askedExam = body.exam && body.exam.componentId && body.exam.optionId;
  const component = askedExam ? COMPONENTS[body.exam.componentId] : null;
  const option = askedExam ? optionById(body.exam.optionId) : null;
  const wantExam = Boolean(component && option && option.componentId === component.id);

  const knowledgePlan = planKnowledge(targetMinutes, wantExam);
  const stageArgs = {
    count: knowledgePlan.count,
    marks: knowledgePlan.marks,
    minutes: knowledgePlan.minutes,
    marksPerQuestion: knowledgePlan.marksPerQuestion,
    pageTitle,
    subjectTitle,
    includedPages,
    notes,
    hasExamStage: wantExam
  };
  const knowledgePrompt =
    knowledgePlan.style === "recall" ? buildRecallPrompt(stageArgs) : buildKnowledgePrompt(stageArgs);

  const examPromise = wantExam
    ? buildExamStage(
        {
          componentId: component.id,
          optionId: option.id,
          site: String(body.exam.site || "").slice(0, 120),
          targetMinutes,
          capMinutes: 25 - knowledgePlan.minutes,
          pageTitle,
          includedPages,
          notes
        },
        apiKey
      ).then(
        (stage) => ({ stage, error: null }),
        (e) => ({ stage: null, error: e.message || "The exam questions failed to generate." })
      )
    : Promise.resolve({ stage: null, error: null });

  let generated;
  let examOut;
  try {
    const both = await Promise.all([
      callGemini(knowledgePrompt.system, knowledgePrompt.user, KNOWLEDGE_SCHEMA, apiKey),
      examPromise
    ]);
    generated = both[0];
    examOut = both[1];
  } catch (e) {
    return send(res, e.status || 502, {
      error:
        e.status === 429
          ? "Every Gemini model is rate limiting right now. Wait a minute and try again."
          : "Couldn't build the practise: " + e.message
    });
  }

  const seen = new Set();
  const questions = [];
  (generated.questions || []).forEach((raw) => {
    const q = normaliseKnowledge(raw || {}, questions.length + 1, knowledgePlan.style);
    if (!q) return;
    const fingerprint = q.prompt.toLowerCase().replace(/[^a-z0-9 ]/g, "").slice(0, 80);
    if (seen.has(fingerprint)) return;
    seen.add(fingerprint);
    questions.push(q);
  });

  const minimum = knowledgePlan.style === "recall" ? 4 : 3;
  if (questions.length < minimum) {
    return send(res, 502, { error: "Gemini returned too few usable questions. Try again." });
  }

  const kept = questions.slice(0, knowledgePlan.count);
  const knowledgeMarks = kept.reduce((sum, q) => sum + q.marks, 0);
  const exam = examOut.stage;

  return send(res, 200, {
    practise: {
      title: String(generated.title || "").trim().slice(0, 90) || pageTitle || "Practise",
      targetMinutes,
      knowledge: {
        style: knowledgePlan.style,
        minutes: knowledgePlan.minutes,
        marks: knowledgeMarks,
        questions: kept
      },
      exam,
      examError: exam ? null : examOut.error,
      allowedMinutes: allowedMinutes(knowledgePlan.minutes, exam ? exam.minutes : 0),
      totalMarks: knowledgeMarks + (exam ? exam.marks : 0),
      generatedAt: Date.now(),
      model: lastModelUsed()
    }
  });
}
